export const ADD_ALL_COUNTRIES = 'ADD_ALL_COUNTRIES'
export const GET_COUNTRY_BY_ID = 'GET_COUNTRY_BY_ID'
export const CLEAR_DETAIL = 'CLEAR_DETAIL'
export const GET_COUNTRY_BY_NAME = 'GET_COUNTRY_BY_NAME'